### ISSUE TITLE
Suggested readme improvements

### ISSUE THREAD

**Issue by BenHizak** [Gruntfuggly/mermaid-export#2]
Hi,

I am struggling with this extension. I'd like to suggest the following improvements to the readme:

- make it clear where the file is exported to by default (I still can't find the output)
- make it clear where the command is to be found (turns out it's `ctrl+shift+P`)
- Make it clear where to see the log (turns out you need to select mermaid-export in Output which is `ctrl+shift+U`)
- make it clear what file extension is required

**Comment by Gruntfuggly** [comment]
It should export the image into the same folder as the the source file - it just replaces the extension with the extension for the chosen output type (defaulting to png)  and any source extension can be used.

I'll add some extra details to the README.md.
